# Generated by Django 2.2.1 on 2019-06-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_auto_20190605_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
